### ISSUE TITLE
RuntimeError: Ninja is required to load C++ extensions

### ISSUE THREAD

**Issue by HaFred** [BradMcDanel/column-combine#2]
Hi @BradMcDanel , I have installed `pytorch==1.3.1, ninja==1.10.2`, but I still came across the following errors when I ran the cifar10 example as shown in readme. Is it possibly some dependencies issue?
```
Traceback (most recent call last):
  File "/home/zhongad/.conda/envs/test_mat/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 893, in verify_ninja_availability
    subprocess.check_call('ninja --version'.split(), stdout=devnull)
  File "/home/zhongad/.conda/envs/test_mat/lib/python3.6/subprocess.py", line 306, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/home/zhongad/.conda/envs/test_mat/lib/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/zhongad/.conda/envs/test_mat/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/home/zhongad/.conda/envs/test_mat/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ninja': 'ninja'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhongad/PycharmProjects/HTKung/train.py", line 17, in <module>
    import util
  File "/home/zhongad/PycharmProjects/HTKung/util.py", line 12, in <module>
    import net
  File "/home/zhongad/PycharmProjects/HTKung/net.py", line 15, in <module>
    sources=['kernels/shift_cuda.cpp', 'kernels/shift_cuda_kernel.cu'])
  File "/home/zhongad/.conda/envs/test_mat/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 661, in load
    is_python_module)
  File "/home/zhongad/.conda/envs/test_mat/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 830, in _jit_compile
    with_cuda=with_cuda)
  File "/home/zhongad/.conda/envs/test_mat/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 853, in _write_ninja_file_and_build
    verify_ninja_availability()
  File "/home/zhongad/.conda/envs/test_mat/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 895, in verify_ninja_availability
    raise RuntimeError("Ninja is required to load C++ extensions")
RuntimeError: Ninja is required to load C++ extensions

Process finished with exit code 1
```

**Comment by BradMcDanel** [comment]
You may need a newer version of ninja (seems like ninja >= 1.8). I have run into similar issues in the past and don't remember how I solved them.

**Comment by HaFred** [comment]
> You may need a newer version of ninja (seems like ninja >= 1.8). I have run into similar issues in the past and don't remember how I solved them.

Thanks for the info, Brad. Actually, I mentioned that I have installed `ninja == 1.10.2`, somehow the python interpreter just cannot access it correctly. I wonder is it possible to import the functions in `'kernels/shift_cuda.cpp', 'kernels/shift_cuda_kernel.cu'`, without using ninja?
